# config
cover: /img/bg_img.jpg
logo: http://7bv937.com1.z0.glb.clouddn.com/qcyoung/TKL/logo.png
logoc: http://7bv937.com1.z0.glb.clouddn.com/qcyoung/TKL/oursbrun.png
top_saying:
- title: GLAD TO SEE U, WELCOME TO YANGZJ1992 'S BLOG.  
- content: 每一个不曾起舞的日子都是对生命的辜负 —— 尼采 《查拉图斯特拉如是说》
bottom_saying:  奇迹每天都在发生 (Miracles happen every day) —— 《阿甘正传》
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#duoshuo name
duoshuo_shortname: yangzj1992

# Miscellaneous
github: https://github.com/yangzj1992
weibo: http://weibo.com/yangzj1992
twitter: https://twitter.com/yangzj1992

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
- name: Kieran
  link: http://go.kieran.top/


#Analytics
cnzz: true  
cnzzaccount: 1000263347

img_server: 


